language: ruby
cache: bundler
rvm:
  - ruby-2.1.2

before_install:
  - openssl aes-256-cbc -K $encrypted_a470fe2bff2c_key -iv $encrypted_a470fe2bff2c_iv -in travis-ssh.tar.enc -out travis-ssh.tar -d
  - tar xvf travis-ssh.tar
  - sudo chmod 600 SoftWEAR-MockBot.pem
  - sudo chmod 600 travis_id_rsa
  - 'eval "$(ssh-agent -s)"'
  - ssh-add SoftWEAR-MockBot.pem travis_id_rsa
  - "ssh -T git@github.com || :"
  - sudo apt-get install libmysql-ruby libmysqlclient-dev ruby-dev libappindicator1 fonts-liberation 
  - gem update --system 2.6.1
  - gem update bundler
  - gem install eventmachine -v 1.0.3 --no-ri --no-rdoc
  - gem install softwear-lib --no-ri --no-rdoc
  - wget http://chromedriver.storage.googleapis.com/2.11/chromedriver_linux64.zip
  - mkdir ~/chromedriver
  - unzip chromedriver_linux64.zip -d ~/chromedriver
  - wget http://security.ubuntu.com/ubuntu/pool/universe/c/chromium-browser/chromium-browser_37.0.2062.120-0ubuntu0.12.04.3_amd64.deb
  - sudo dpkg -i chromium-browser_37.0.2062.120-0ubuntu0.12.04.3_amd64.deb

before_script:
  - |
    cat <<END >> config/database.yml
      db: &db
        adapter: mysql2
        database: prd-test
        username: travis

      test:
        <<: *db
      production:
        <<: *db
    END
  - export PATH=$PATH:~/chromedriver
  - bundle exec rake db:create
  - bundle exec rake db:migrate

script: xvfb-run --server-args="-screen 0, 1024x768x24" bundle exec rspec -f d -t ~no_ci && bundle exec softwear-deploy
